---
- name: push script
  copy:
    src: '{{ bench.script }}'
    dest: '/tmp/{{ bench.script | basename }}'
    mode: 0755

- name: check if we have host-specific environment
  set_fact:
    env_host_map: '{{ bench.environment_host | default({}) }}'

- local_action:
    module: debug
    msg: 'executing: {{ bench_params | combine(bench.environment) | combine(env_host_map[inventory_hostname] | default({}))}}'
  run_once: true

- name: run script
  shell: '/tmp/{{ bench.script | basename }}'
  async: '{{ bench.test_timeout | default(test_timeout | default(6000)) }}'
  environment: '{{ bench_params | combine(bench.environment) | combine(env_host_map[inventory_hostname] | default({}))}}'
  poll: 20
  register: script_async

- name: get output
  async_status:
    jid: '{{ script_async.ansible_job_id }}'
  register: script_result

- name: set fact to store result of bench execution
  local_action:
    module: set_fact
    bench_run_result: '{{ script_result.rc }}'
    wait_result: 'hosts finished running'
  run_once: true

- name: record elapsed time in output folder
  local_action:
    module: copy
    content: '{{ script_result.delta }}'
    dest: '{{ output_folder }}/runtime'

- name: capture stdout
  local_action:
    module: copy
    content: '{{ script_result.stdout }}'
    dest: '{{ output_folder }}/std.out'

- name: capture stderr
  local_action:
    module: copy
    content: '{{ script_result.stderr }}'
    dest: '{{ output_folder }}/std.err'
