---
- debug:
    msg: 'playbook_dir: {{ playbook_dir }}'

- name: push script
  copy:
    src: '{{ bench.script_src_dir }}/{{ bench.script_file }}'
    dest: '/tmp/{{ bench.script_file }}'
    mode: 0755

- name: run script
  shell: '/tmp/{{ bench.script_file }}'
  async: '{{ bench.test_timeout | default(test_timeout | default(6000)) }}'
  poll: 20
  register: script_async
  when: run_raw is not defined or not run_raw

- name: get output
  async_status:
    jid: '{{ script_async.ansible_job_id }}'
  register: script_result
  when: run_raw is not defined or not run_raw

- name: run script raw
  raw: '/tmp/{{ bench.script_file }}'
  register: script_result
  when: run_raw is defined and run_raw

- name: set fact to store result of bench execution
  local_action:
    module: set_fact
    bench_run_result: '{{ script_result.rc }}'
    wait_result: 'hosts finished running'
  run_once: true

- name: record elapsed time in output folder
  local_action:
    module: copy
    content: '{{ script_result.delta }}'
    dest: '{{ output_folder }}/runtime'
  when: run_raw is not defined or not run_raw

- name: capture stdout
  local_action:
    module: copy
    content: '{{ script_result.stdout }}'
    dest: '{{ output_folder }}/std.out'

- name: capture stderr
  local_action:
    module: copy
    content: '{{ script_result.stderr }}'
    dest: '{{ output_folder }}/std.err'
...
